### ISSUE TITLE
ToastContainer

### ISSUE THREAD

**Issue by hannespreishuber** [heckradr/BlazorLab6#1]
das Lab funktioniert so nicht (wie du ja angemerkt hast) 

einfach nach den Router verschieben

```
<Router AppAssembly="typeof(Program).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="routeData" DefaultLayout="typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="routeData" Selector="h1" />
    </Found>
</Router>
<ToastContainer></ToastContainer>
````

Vermutich habe ich irgendeinen anderen Rendermode betrieben. Jedenfalls ist das auch der Grund war das Event null war

**Comment by heckradr** [comment]
@hannespreishuber vielen Dank jetzt klappt es
